apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssu-mgmt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.service.scrapeMetrics }}
    scrape-service-metrics: "true"
    {{- end }}
    {{- include "ssu-mgmt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: external
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ssu-mgmt.selectorLabels" . | nindent 4 }}
